language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: M1kpNOPzfzos0nXCojlkmPN+I6zDhWU2fcwT+IlrjsS6wXjz0pgc4flpgiTVo56SRHxCGM2YYJcq/p437Bs8LGWSR1Xe3yCDHfPJVXnguvxHDrO1a4wgtK5Fv008iZXKdNEIRF+PswFcrOmTuknC3AsImmoopuBwKBDcIBTWcFxX3pI7ySd3X0Dte/nc90jYAjz9uDAEkKUuZFwIOCTJXrsXwZDq8itWFr7OVgieDLn7K0TBSzshkq4kkUD/XFnfEbFnl+SHLSBocjT3DizqtmqJ+RGSKg58ncFZGghph1KG2wLvkYt1FN6Yzz0uXjFLlkN2wV6q6vJwraelfRv+wLfCEmR378Qln+146DDjlJE0MalI9mw41l7WluQyAphggUTr6KVVsSdES6eo+mMoh41A1aVW1Wc4tS/ahw2p+AKpoe1PtIETL7dFz/iPb1NwIMLzbEQ7jx1IoUIb8+/J9ZmbCbNOgSi+TZtM5F2mhK+SkIdvyzqAVctsC9SCXOVB/RkhrQFXxKEHKnAl1osg5cg25GyyrbWL7IPJslPNMC2XT/LXAAwihpXUYJAnt5fIFtUx2/eMyg5tBAA024QRaWJ6VZal3gh3RqG+eLkA8C8uJPeoaqvF+EBW92SwSrLUhvEG2FLzkT1IpMnxJrOYNtFMJWUrXBLc3nVHC+YfQJw=
  - secure: aL34X/1lpvPYyGfPVUn9H34wdx9BYZEt7Owo5UcVAYdeU7UEkKbmfAPU6aF1Z6Osm1M+wo01a5vksqqBx+TV5WuY35a6wwLkpFAZqnR37F3xxMco5Ox4ADB9+Cy3r/kuWRnUpGz09ADqSqHGTa/P/PFJTOTj+w7DWUg4dPDo8VBSoD97TDwbSKrKv8CNAraHGu/hUQgmXGC+tLNQMMs9xKry/rBAQK0EmjLwKGVEnFrWnjo69IH1hzqiVwSE0WdLkUN+m7IJHn3I77DUmc4CRQUiYil5zY8hEdivHO+2Dg6tkNlRzcwuFQVMPiSa1Cc9wPqtVP4x/nAvAf9PgxmnL3/r8irzVwUR71smW+viQyTuSGNePm6xuSa8W/B8Zaba7ElriL2u4jDqxwDQM5ugcjz5DzskpLHxZWEkrZjydoacwInnzvqgQzhrPKG9XX5IufORBTE5kgNBRdwMh5g+gz5JgTS1tofGxS6hviK6QEPyoNtjloPMLm9YZ0ozePeJ9CEOD9aKkWp8k3mToPx2lBuvVQiBwxGKs70f36c4tuIv209/j5wn383pALfnKN+XgeCE/6F40jXEA3uLZqoDxuDkJy6+sa6zt/1BGaFV2ezRV2rdNTQWRRScLbKp5U7mZfOcYxTV/iTPJI2kwhiMGamEKXfJ3HlBJpH67SYSgLQ=
